---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    state: present

- name: "Install npm"
  become: yes
  apt:
    name: npm
    state: present

- name: "Install pm2"
  become: yes
  command: npm install pm2 -g

- name: Creates web directory
  file:
    path: /tmp/web
    state: directory

- name: copy artifact
  copy:
    src: artifact.tar.gz
    dest: /tmp/web/artifact.tar.gz

# - name: ls comm
#   become: yes
#   command: cd /tmp/web && ls

- unarchive:
    src:  /tmp/web/artifact.tar.gz
    dest: /tmp/web

- name: "stop web server"
  become: yes
  command: pm2 stop default

- name: "start web server"
  become: yes
  command: cd /tmp/web && pm2 start npm -- start # pm2 start ~/web/index.js -f