---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    state: present

- name: "Install npm"
  become: yes
  apt:
    name: npm
    state: present

- name: "Install pm2"
  become: yes
  command: npm install pm2 -g

- name: Creates web directory
  become: yes
  file:
    state: directory
    path: /etc/web

- name: Creates artifact directory
  become: yes
  file:
    state: directory
    path: /etc/web/artifact

- name: copy artifact
  become: yes
  copy:
    src: ../files/artifact.tar.gz
    dest: /etc/web/artifact.tar.gz

- name: Make my directory tree readable
  become: yes
  file:
    path: /etc/web
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: chmod
  become: yes
  command: chmod 777 /etc/web/artifact.tar.gz

- name: unarchive
  become: yes
  command: tar -xf /etc/web/artifact.tar.gz -C /etc/web/artifact

# - name: "stop web server"
#   become: yes
#   command: pm2 stop default

# - name: "start web server"
#   become: yes
#   command: pm2 start npm -- start # pm2 start ~/web/index.js -f
- name: "export env variables"
  shell: |
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

- name: "start web server shell"
  shell: |
    cd /etc/web/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start -i 3030
    #  npm run start