version: 2.1
# orbs:
#   slack: circleci/slack@4.10.1
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    # parameters:
    #   - environment:
    #       default: "world"
    #       type: string 
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
       #     exit 1

jobs:
  # build:
  #   machine: true
  #   steps:
  #     - run: some build command
  #     - slack/notify:
  #         branch_pattern: main
  #         event: fail
  #         template: basic_fail_1
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
              # Your code here
              cd backend
              npm install
              npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: test front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run test
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-test
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: test back-end
          command: |
            # Your code here
            cd backend
            npm install
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: scan fron-end
          command: |
            # Your code here
            cd frontend
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force
            # If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
            npm audit --audit-level=critical


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: scan back-end
          command: |
            # Your code here
            cd backend
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force
            # If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
            npm audit --audit-level=critical  
            

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=cicdProject \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=cicdProject \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:project,Values=cicdProject" \
            --output text | tee -a .circleci/ansible/inventory.txt
      - run:
          name: cat inventory file
          command: |
            cat .circleci/ansible/inventory.txt
            cp .circleci/ansible/inventory.txt /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - inventory.txt
    #  - destroy-environment
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: copy inventory
          command: |
            cp /tmp/inventory.txt .circleci/ansible/
            # echo "[web]" > .circleci/ansible/inventory.txt
            # echo "54.187.195.121" >> .circleci/ansible/inventory.txt
            # echo "54.185.238.15" >> .circleci/ansible/inventory.txt
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["9f:31:95:1b:c8:bb:fe:df:bf:d6:76:01:07:fb:ef:f1"]
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
            apk add --update ansible
      - run:
          name: fix ssh issue
          command: |
            # Install Ansible

            apk add --no-cache openssh-client
      - run:
          name: fix ssh issue 2
          command: |
            echo "Host *" >> /etc/ssh/ssh_config &&\
            echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
            #ssh -o StrictHostKeyChecking=no
      - run:
          name: Run Playbook and Configure server
          command: |
            # Your command
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml
      # Here's where you will add some code to rollback on failure                

  run-migrations:
    docker:
      - image: cimg/node:12.22.10
    steps:
      - checkout
      - restore_cache:
          paths: [backend/node_modules]
          key: backend-build
      - run:
          name: Run migrations
          command: |
            cd backend
            rm -r node_modules
            rm package-lock.json
            npm install
            # npm audit fix 
            # npm audit fix --audit-level=critical --force
            # npm audit
            # Run and save the migration output
            npm run migrations > migrations_dump.txt
      - run:
          name: Send migration results to memstash
          command: | 
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
              #  curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
                curl https://kvdb.io/BaBUKPcutaG5oSneVWB6z1/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
            fi
     # Here's where you will add some code to rollback on failure    

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - run:
      #     name: Install ansible
      #     command: |
      #       sudo yum -y update
      #       sudo yum install -y epel-release
      #       yum install -y ansible
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: install node and npm
          command: |
            curl -sL https://rpm.nodesource.com/setup_8.x | bash -
            yum install -y nodejs
          #  apk add --update npm
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:project,Values=cicdProject" \
            --output text )
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      # Here's where you will add some code to rollback on failure  
                 
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      # - restore_cache:
      #     keys: [backend-build]
      # - restore_cache:
      #     paths: [backend/node_modules]
      #     key: backend-build
      - checkout
      - restore_cache:
          paths: [backend/node_modules]
          key: backend-build
      - attach_workspace:
          at: /tmp
      - run:
          name: copy inventory
          command: |
            cp /tmp/inventory.txt .circleci/ansible/
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["9f:31:95:1b:c8:bb:fe:df:bf:d6:76:01:07:fb:ef:f1"]
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
            apk add --update ansible
      - run:
          name: Install node and npm
          command: |
            apk add --update nodejs npm
      - run:
          name: install tar
          command: |
            apk add --no-cache tar \
            gzip
      - run:
          name: fix ssh issue
          command: |
            apk add --no-cache openssh-client
      - run:
          name: fix ssh issue 2
          command: |
            echo "Host *" >> /etc/ssh/ssh_config &&\
            echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
            #ssh -o StrictHostKeyChecking=no
      - run:
          name: Run Playbook and Configure server
          command: |
            # Your command
            cd backend
            npm i
            npm run build
            cd ..
            # Zip the directory
            tar -C backend -czvf artifact.tar.gz .
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is -------"
            cat inventory.txt
            ansible-playbook -i inventory.txt deploy-backend.yml
      # Here's where you will add some code to rollback on failure    

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: copy inventory
          command: |
            cp /tmp/inventory.txt .circleci/ansible/
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add curl
            # your code here
      - run:
          name: Get backend url
          command: |
              BACKEND_IP= grep -m 2 -o '.*' .circleci/ansible/inventory.txt | cut -d ':' -f 1 | tail -n 1
              # $(cat .circleci/ansible/inventory.txt)
      - run:
          name: Backend smoke test.
          command: |
              # Fetch and prepare the BACKEND_IP env var
              export API_URL="http://${BACKEND_IP}:3030"
              echo "${API_URL}"
              if curl "${API_URL}/api/status" | grep "ok"
              then
                  return 0
              else
                  return 1
              fi
      - run:
          name: Frontend smoke test.
          command: |
              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
              echo ${URL} 
              if curl -s ${URL} | grep "Welcome"
              then
                  # Change this to 0 after the job fails
                return 1
              else
                return 1
              fi
      # Here's where you will add some code to rollback on failure  

workflows:
  default:
    jobs:
     ## - build:
     ##    context: slack-secrets
      - build-frontend
      - build-backend
      # - test-frontend:
      #     requires: [build-frontend]
      # - test-backend:
      #     requires: [build-backend]
      # - scan-frontend:
      #     requires: [build-frontend]
      # - scan-backend:
      #     requires: [build-backend]
#       - deploy-infrastructure:
#           requires: [scan-frontend]
#  ##     - configure-infrastructure
#       - configure-infrastructure:
#           requires: [deploy-infrastructure]
#       - run-migrations:
#           requires: [configure-infrastructure]
#  ##     - deploy-frontend
#       - deploy-frontend:
#           requires: [run-migrations]

  #     - deploy-infrastructure:
  #         requires: [build-frontend,build-backend]
  #     - configure-infrastructure:
  #         requires: [deploy-infrastructure]
  #   #  - run-migrations:
  #  #       requires: [configure-infrastructure]
  # #    - deploy-frontend:
  #  #       requires: [configure-infrastructure]
  #     - deploy-backend:
  #         requires: [configure-infrastructure]
  #   #  - run-migrations


   #   - deploy-backend:
   #       requires: [build-backend]

      # - fix-deploy-infrastructure
      # - test-deploy-infrastructure:
      #      requires: [fix-deploy-infrastructure]
      - deploy-infrastructure:
          requires: [build-frontend,build-backend]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - deploy-frontend:
          requires: [configure-infrastructure]
      - deploy-backend:
          requires: [configure-infrastructure]
      - smoke-test:
          requires: [deploy-backend,deploy-frontend]
 
 
 #       - configure-infrastructure